trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '$(Build.SourcesDirectory)/examples'

  - script: cd examples && make

- job: macOS
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '$(Build.SourcesDirectory)/examples'

  - script: cd examples && make

- job: Windows
  pool:
    vmImage: 'windows-2019'

  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '-A x64 -DCMAKE_HOST_SYSTEM_NAME=Windows $(Build.SourcesDirectory)'

  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)/examples/*.sln'
      maximumCpuCount: true
      platform: 'x64'
