trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: cd examples && make

- job: macOS
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - script: cd examples && gcc -o examples *.c -DUNIX -Wall -g

- job: Windows
  pool:
    vmImage: 'windows-2019'

  steps:
  - script: cd examples && gcc -o examples.exe *.c -DWINDOWS -Wall -g 
